'use client';

export interface ClassMetadata {
  commonName: string;
  soundType?: string;
  description?: string;
}

const CLASS_MAPPINGS: Record<string, ClassMetadata> = {
  'ACCO1': { commonName: 'American Crow', soundType: 'call_1' },
  'ACCO2': { commonName: 'American Crow', soundType: 'call_2' },
  'ACCO3': { commonName: 'American Crow', soundType: 'call_3' },
  'ACGE1': { commonName: 'American Goldfinch', soundType: 'call_1' },
  'ACGE2': { commonName: 'American Goldfinch', soundType: 'call_2' },
  'ACST1': { commonName: 'Acorn Woodpecker', soundType: 'call_1' },
  'AEAC1': { commonName: 'Alder Flycatcher', soundType: 'call_1' },
  'AEAC2': { commonName: 'Alder Flycatcher', soundType: 'call_2' },
  'Airplane': { commonName: 'Airplane', soundType: 'engine_1' },
  'ANCA1': { commonName: 'Anna\'s Hummingbird', soundType: 'call_1' },
  'ASOT1': { commonName: 'Ash-throated Flycatcher', soundType: 'call_1' },
  'BOUM1': { commonName: 'Band-tailed Pigeon', soundType: 'call_1' },
  'BRCA1': { commonName: 'Brown Creeper', soundType: 'call_1' },
  'BRMA1': { commonName: 'Brewer\'s Blackbird', soundType: 'call_1' },
  'BRMA2': { commonName: 'Brewer\'s Blackbird', soundType: 'call_2' },
  'BUJA1': { commonName: 'Bullock\'s Oriole', soundType: 'call_1' },
  'BUJA2': { commonName: 'Bullock\'s Oriole', soundType: 'call_2' },
  'Bullfrog': { commonName: 'American Bullfrog', soundType: 'chorus_1' },
  'BUVI1': { commonName: 'Bushtit', soundType: 'call_1' },
  'BUVI2': { commonName: 'Bushtit', soundType: 'call_2' },
  'CACA1': { commonName: 'California Scrub-Jay', soundType: 'call_1' },
  'CAGU1': { commonName: 'California Quail', soundType: 'call_1' },
  'CAGU2': { commonName: 'California Quail', soundType: 'call_2' },
  'CAGU3': { commonName: 'California Quail', soundType: 'call_3' },
  'CALA1': { commonName: 'California Thrasher', soundType: 'call_1' },
  'CALU1': { commonName: 'California Towhee', soundType: 'call_1' },
  'CAPU1': { commonName: 'Cassin\'s Vireo', soundType: 'call_1' },
  'CAUS1': { commonName: 'Cassin\'s Auklet', soundType: 'call_1' },
  'CAUS2': { commonName: 'Cassin\'s Auklet', soundType: 'call_2' },
  'CCOO1': { commonName: 'Common Cuckoo', soundType: 'call_1' },
  'CCOO2': { commonName: 'Common Cuckoo', soundType: 'call_2' },
  'CECA1': { commonName: 'Cedar Waxwing', soundType: 'call_1' },
  'Chainsaw': { commonName: 'Chainsaw', soundType: 'engine_1' },
  'CHFA1': { commonName: 'Chestnut-backed Chickadee', soundType: 'call_1' },
  'CHFA2': { commonName: 'Chestnut-backed Chickadee', soundType: 'call_2' },
  'CHFA3': { commonName: 'Chestnut-backed Chickadee', soundType: 'call_3' },
  'Chicken': { commonName: 'Rooster (Red Junglefowl)', soundType: 'song_1' },
  'CHMI1': { commonName: 'Chipping Sparrow', soundType: 'call_1' },
  'CHMI2': { commonName: 'Chipping Sparrow', soundType: 'call_2' },
  'COAU1': { commonName: 'Cooper\'s Hawk', soundType: 'call_1' },
  'COAU2': { commonName: 'Cooper\'s Hawk', soundType: 'call_2' },
  'COBR1': { commonName: 'Common Raven', soundType: 'call_1' },
  'COCO1': { commonName: 'Common Nighthawk', soundType: 'call_1' },
  'COSO1': { commonName: 'Common Yellowthroat', soundType: 'call_1' },
  'Cow': { commonName: 'Brown-headed Cowbird', soundType: 'song_1' },
  'Creek': { commonName: 'Creek', soundType: 'water' },
  'Cricket': { commonName: 'Cricket', soundType: 'chirp' },
  'CYST1': { commonName: 'Canyon Wren', soundType: 'call_1' },
  'CYST2': { commonName: 'Canyon Wren', soundType: 'call_2' },
  'DEFU1': { commonName: 'Dark-eyed Junco', soundType: 'call_1' },
  'DEFU2': { commonName: 'Dark-eyed Junco', soundType: 'call_2' },
  'Dog': { commonName: 'Dog', soundType: 'bark_1' },
  'DRPU1': { commonName: 'Downy Woodpecker', soundType: 'call_1' },
  'Drum': { commonName: 'Woodpecker drum', soundType: 'drum' },
  'EMDI1': { commonName: 'Empidonax sp.', soundType: 'call_1' },
  'EMOB1': { commonName: 'Empidonax sp.', soundType: 'call_2' },
  'FACO1': { commonName: 'Falcon sp.', soundType: 'call_1' },
  'FASP1': { commonName: 'Flycatcher sp.', soundType: 'call_1' },
  'Fly': { commonName: 'Dusky Flycatcher', soundType: 'song_1' },
  'Frog': { commonName: 'Amphibian', soundType: 'chorus_1' },
  'GADE1': { commonName: 'Gadwall', soundType: 'call_1' },
  'GLGN1': { commonName: 'Glaucous-winged Gull', soundType: 'call_1' },
  'Growler': { commonName: 'Growler', soundType: 'engine' },
  'Gunshot': { commonName: 'Gunshot', soundType: 'shot_1' },
  'HALE1': { commonName: 'Hairy Woodpecker', soundType: 'call_1' },
  'HAPU1': { commonName: 'Hammond\'s Flycatcher', soundType: 'call_1' },
  'HEVE1': { commonName: 'Hermit Thrush', soundType: 'call_1' },
  'Highway': { commonName: 'Highway', soundType: 'traffic' },
  'Horn': { commonName: 'Truck beep', soundType: 'beep_1' },
  'Human': { commonName: 'Human', soundType: 'speech_1' },
  'HYPI1': { commonName: 'Hutton\'s Vireo', soundType: 'call_1' },
  'IXNA1': { commonName: 'Ixoreus naevius', soundType: 'call_1' },
  'IXNA2': { commonName: 'Ixoreus naevius', soundType: 'call_2' },
  'JUHY1': { commonName: 'Junco hyemalis', soundType: 'call_1' },
  'LEAL1': { commonName: 'Leiothlypis celata', soundType: 'call_1' },
  'LECE1': { commonName: 'Leiothlypis celata', soundType: 'call_2' },
  'LEVI1': { commonName: 'Leiothlypis ruficapilla', soundType: 'call_1' },
  'LEVI2': { commonName: 'Leiothlypis ruficapilla', soundType: 'call_2' },
  'LOCU1': { commonName: 'Loxia curvirostra', soundType: 'call_1' },
  'MEFO1': { commonName: 'Melospiza melodia', soundType: 'call_1' },
  'MEGA1': { commonName: 'Mega sp.', soundType: 'call_1' },
  'MEKE1': { commonName: 'Melospiza georgiana', soundType: 'call_1' },
  'MEKE2': { commonName: 'Melospiza georgiana', soundType: 'call_2' },
  'MEKE3': { commonName: 'Melospiza georgiana', soundType: 'call_3' },
  'MYTO1': { commonName: 'Myadestes townsendi', soundType: 'call_1' },
  'NUCO1': { commonName: 'Nucifraga columbiana', soundType: 'call_1' },
  'OCPR1': { commonName: 'Oreortyx pictus', soundType: 'call_1' },
  'ODOC1': { commonName: 'Odocoileus sp.', soundType: 'call_1' },
  'ORPI1': { commonName: 'Oreortyx pictus', soundType: 'call_1' },
  'ORPI2': { commonName: 'Oreortyx pictus', soundType: 'call_2' },
  'PAFA1': { commonName: 'Pacific Wren', soundType: 'call_1' },
  'PAFA2': { commonName: 'Pacific Wren', soundType: 'call_2' },
  'PAHA1': { commonName: 'Pandion haliaetus', soundType: 'call_1' },
  'PECA1': { commonName: 'Perisoreus canadensis', soundType: 'call_1' },
  'PHME1': { commonName: 'Pheucticus melanocephalus', soundType: 'call_1' },
  'PHNU1': { commonName: 'Phalacrocorax penicillatus', soundType: 'call_1' },
  'PILU1': { commonName: 'Pileated Woodpecker', soundType: 'call_1' },
  'PILU2': { commonName: 'Pileated Woodpecker', soundType: 'call_2' },
  'PIMA1': { commonName: 'Pipilo maculatus', soundType: 'call_1' },
  'PIMA2': { commonName: 'Pipilo maculatus', soundType: 'call_2' },
  'POEC1': { commonName: 'Poecile atricapillus', soundType: 'call_1' },
  'POEC2': { commonName: 'Poecile atricapillus', soundType: 'call_2' },
  'PSFL1': { commonName: 'Pacific-slope Flycatcher', soundType: 'call_1' },
  'Rain': { commonName: 'Rain', soundType: 'rain_1' },
  'Raptor': { commonName: 'Raptor', soundType: 'call' },
  'SICU1': { commonName: 'Sitta canadensis', soundType: 'call_1' },
  'SITT1': { commonName: 'Sitta pygmaea', soundType: 'call_1' },
  'SITT2': { commonName: 'Sitta pygmaea', soundType: 'call_2' },
  'SPHY1': { commonName: 'Sphyrapicus ruber', soundType: 'call_1' },
  'SPHY2': { commonName: 'Sphyrapicus ruber', soundType: 'call_2' },
  'SPPA1': { commonName: 'Spizella passerina', soundType: 'call_1' },
  'SPPI1': { commonName: 'Spinus pinus', soundType: 'call_1' },
  'SPTH1': { commonName: 'Spotted Towhee', soundType: 'call_1' },
  'STDE1': { commonName: 'Strix varia', soundType: 'call_1' },
  'STNE1': { commonName: 'Strix nebulosa', soundType: 'call_1' },
  'STNE2': { commonName: 'Strix nebulosa', soundType: 'call_2' },
  'STOC_4Note': { commonName: 'Northern Spotted Owl', soundType: 'call_1' },
  'STOC_Series': { commonName: 'Northern Spotted Owl', soundType: 'call_2' },
  'Strix_Bark': { commonName: 'Barred Owl', soundType: 'call_3' },
  'Strix_Whistle': { commonName: 'Barred Owl', soundType: 'call_1' },
  'STVA_8Note': { commonName: 'Varied Thrush', soundType: 'song_1' },
  'STVA_Insp': { commonName: 'Varied Thrush', soundType: 'call_1' },
  'STVA_Series': { commonName: 'Varied Thrush', soundType: 'call_2' },
  'Survey_Tone': { commonName: 'Survey Tone', soundType: 'tone' },
  'TADO1': { commonName: 'Tachycineta bicolor', soundType: 'call_1' },
  'TADO2': { commonName: 'Tachycineta bicolor', soundType: 'call_2' },
  'TAMI1': { commonName: 'Tamiasciurus douglasii', soundType: 'call_1' },
  'Thunder': { commonName: 'Thunder', soundType: 'thunder' },
  'TRAE1': { commonName: 'Troglodytes aedon', soundType: 'call_1' },
  'Train': { commonName: 'Train', soundType: 'engine' },
  'Tree': { commonName: 'Tree creak', soundType: 'creak_1' },
  'TUMI1': { commonName: 'Turdus migratorius', soundType: 'call_1' },
  'TUMI2': { commonName: 'Turdus migratorius', soundType: 'call_2' },
  'URAM1': { commonName: 'Uramus sp.', soundType: 'call_1' },
  'VIHU1': { commonName: 'Vireo huttoni', soundType: 'call_1' },
  'Wildcat': { commonName: 'Wildcat', soundType: 'call' },
  'Yarder': { commonName: 'Yarder', soundType: 'engine_1' },
  'ZEMA1': { commonName: 'Zonotrichia leucophrys', soundType: 'call_1' },
  'ZOLE1': { commonName: 'Zonotrichia leucophrys', soundType: 'call_2' },
};

export async function getClassMetadata(className: string): Promise<ClassMetadata | null> {
  return CLASS_MAPPINGS[className] ?? null;
}

export async function getHumanReadableName(className: string): Promise<string> {
  const metadata = await getClassMetadata(className);
  
  if (metadata) {
    if (metadata.soundType && metadata.soundType !== 'call' && metadata.soundType !== 'song') {
      return `${metadata.commonName} (${metadata.soundType})`;
    }
    return metadata.commonName;
  }
  
  return className;
}

export async function getClassDescription(className: string): Promise<string | null> {
  const metadata = await getClassMetadata(className);
  return metadata?.description ?? null;
}
